In [2]:
import pandas as pd

### Importing Data

In [3]:
delivery_df = pd.read_csv('deliveries.csv')
matches_df = pd.read_csv('matches.csv')

In [4]:
delivery_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [5]:
matches_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [6]:
delivery_df.shape

(260920, 17)

In [7]:
matches_df.shape

(1095, 20)

In [8]:
delivery_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

In [9]:
matches_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

In [10]:
delivery_df.dtypes

match_id            int64
inning              int64
batting_team          str
bowling_team          str
over                int64
ball                int64
batter                str
bowler                str
non_striker           str
batsman_runs        int64
extra_runs          int64
total_runs          int64
extras_type           str
is_wicket           int64
player_dismissed      str
dismissal_kind        str
fielder               str
dtype: object

In [11]:
matches_df.dtypes

id                   int64
season                 str
city                   str
date                   str
match_type             str
player_of_match        str
venue                  str
team1                  str
team2                  str
toss_winner            str
toss_decision          str
winner                 str
result                 str
result_margin      float64
target_runs        float64
target_overs       float64
super_over             str
method                 str
umpire1                str
umpire2                str
dtype: object

### Data Cleaning and Validation

In [12]:
delivery_df.isnull().head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True

In [13]:
pd.isna(delivery_df).head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True

In [14]:
pd.isna(matches_df).head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [15]:
delivery_df.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [16]:
matches_df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [17]:
delivery_df.describe()

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

In [18]:
matches_df.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [19]:
delivery_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB

In [20]:
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB

In [21]:
matches_df.drop(columns=['method'], inplace=True)

In [22]:
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  umpire1          1095 non-null   str
 18  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(15)
memory usage: 162.7 KB

In [23]:
delivery_df['batting_team'].unique()

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bangalore',
         'Chennai Super Kings',             'Kings XI Punjab',
            'Rajasthan Royals',            'Delhi Daredevils',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [24]:
delivery_df['batting_team'] = delivery_df['batting_team'].replace({'Royal Challengers Bengaluru':'Royal Challengers Bangalore', 
                                                                   'Rising Pune Supergiant':'Rising Pune Supergiants',
                                                                   'Kings XI Punjab': 'Punjab Kings',
                                                                   'Delhi Daredevils': 'Delhi Capitals'})

In [25]:
delivery_df['batting_team'].unique()

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bangalore',
         'Chennai Super Kings',                'Punjab Kings',
            'Rajasthan Royals',              'Delhi Capitals',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',        'Lucknow Super Giants',
              'Gujarat Titans']
Length: 15, dtype: str

In [26]:
delivery_df['bowling_team'].unique()

<StringArray>
['Royal Challengers Bangalore',       'Kolkata Knight Riders',
             'Kings XI Punjab',         'Chennai Super Kings',
            'Delhi Daredevils',            'Rajasthan Royals',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
              'Gujarat Titans',        'Lucknow Super Giants',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [27]:
delivery_df['bowling_team'] = delivery_df['bowling_team'].replace({'Royal Challengers Bengaluru':'Royal Challengers Bangalore', 
                                                                   'Rising Pune Supergiant':'Rising Pune Supergiants',
                                                                   'Kings XI Punjab': 'Punjab Kings',
                                                                   'Delhi Daredevils': 'Delhi Capitals'})

In [28]:
delivery_df['bowling_team'].unique()

<StringArray>
['Royal Challengers Bangalore',       'Kolkata Knight Riders',
                'Punjab Kings',         'Chennai Super Kings',
              'Delhi Capitals',            'Rajasthan Royals',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',              'Gujarat Titans',
        'Lucknow Super Giants']
Length: 15, dtype: str

In [29]:
matches_df['team1'].unique()

<StringArray>
['Royal Challengers Bangalore',             'Kings XI Punjab',
            'Delhi Daredevils',              'Mumbai Indians',
       'Kolkata Knight Riders',            'Rajasthan Royals',
             'Deccan Chargers',         'Chennai Super Kings',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',               'Gujarat Lions',
     'Rising Pune Supergiants',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [30]:
matches_df['team1'] = matches_df['team1'].replace({'Royal Challengers Bengaluru':'Royal Challengers Bangalore', 
                                                                   'Rising Pune Supergiant':'Rising Pune Supergiants',
                                                                   'Kings XI Punjab': 'Punjab Kings',
                                                                   'Delhi Daredevils': 'Delhi Capitals'})

In [31]:
matches_df['team2'] = matches_df['team2'].replace({'Royal Challengers Bengaluru':'Royal Challengers Bangalore', 
                                                                   'Rising Pune Supergiant':'Rising Pune Supergiants',
                                                                   'Kings XI Punjab': 'Punjab Kings',
                                                                   'Delhi Daredevils': 'Delhi Capitals'})

In [32]:
matches_df['team1'].unique()

<StringArray>
['Royal Challengers Bangalore',                'Punjab Kings',
              'Delhi Capitals',              'Mumbai Indians',
       'Kolkata Knight Riders',            'Rajasthan Royals',
             'Deccan Chargers',         'Chennai Super Kings',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',               'Gujarat Lions',
     'Rising Pune Supergiants',        'Lucknow Super Giants',
              'Gujarat Titans']
Length: 15, dtype: str

In [33]:
delivery_df.fillna('None', inplace=True).head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,None,None,None
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,None,None,None
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None

In [34]:
delivery_df.isnull().sum()

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

In [35]:
stadium_to_city = {
    'Dubai International Cricket Stadium': 'Dubai',
    'Sharjah Cricket Stadium': 'Sharjah'
}

matches_df['city'] = matches_df['city'].fillna(matches_df['venue'].map(stadium_to_city))

In [36]:
matches_df.isnull().sum()

id                  0
season              0
city                0
date                0
match_type          0
player_of_match     5
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
winner              5
result              0
result_margin      19
target_runs         3
target_overs        3
super_over          0
umpire1             0
umpire2             0
dtype: int64

In [37]:
# matches_df = matches_df.dropna(subset=['player_of_match', 'winner'])

In [38]:
matches_df['player_of_match'] = matches_df['player_of_match'].fillna('Match Abandoned')
matches_df['winner'] = matches_df['winner'].fillna('Match Abandoned')

In [39]:
matches_df.fillna(0, inplace=True).head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,BF Bowden,K Hariharan

In [40]:
matches_df.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
umpire1            0
umpire2            0
dtype: int64

In [41]:
delivery_df['match_id'].nunique()

1095

In [42]:
matches_df['id'].nunique()

1095

In [43]:
set(matches_df['id']) == set(delivery_df['match_id'])

True

### Data Transformation

In [44]:
matches_df.dtypes

id                   int64
season                 str
city                   str
date                   str
match_type             str
player_of_match        str
venue                  str
team1                  str
team2                  str
toss_winner            str
toss_decision          str
winner                 str
result                 str
result_margin      float64
target_runs        float64
target_overs       float64
super_over             str
umpire1                str
umpire2                str
dtype: object

In [45]:
matches_df['date'] = pd.to_datetime(matches_df['date'])

In [46]:
matches_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,BF Bowden,K Hariharan

In [47]:
delivery_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,None,None,None
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,None,None,None
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None

In [48]:
#Merging dataframes
final_df = delivery_df.merge(matches_df, left_on='match_id', right_on='id')

In [49]:
final_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen

In [50]:
final_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date',
       'match_type', 'player_of_match', 'venue', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin',
       'target_runs', 'target_overs', 'super_over', 'umpire1', 'umpire2'],
      dtype='str')

In [51]:
# final_df.drop(columns='id', inplace=True)

### Core Analysis

#### Total runs per match

In [218]:
# runs_per_match = final_df.groupby('match_id')['total_runs'].sum()


runs_per_match = (
    final_df
    .groupby(['match_id', 'team1', 'team2'])['total_runs']
    .sum()
    .reset_index(name='total_runs_per_match')
)
runs_per_match = runs_per_match.sort_values('total_runs_per_match', ascending=False)

In [219]:
runs_per_match.head(10)

,match_id,team1,team2,total_runs_per_match
1053,1426268,Sunrisers Hyderabad,Royal Challengers Bangalore,549
1031,1422126,Sunrisers Hyderabad,Mumbai Indians,523
1065,1426280,Kolkata Knight Riders,Punjab Kings,523
1066,1426281,Delhi Capitals,Mumbai Indians,504
146,419137,Chennai Super Kings,Rajasthan Royals,469
1058,1426273,Sunrisers Hyderabad,Delhi Capitals,465
679,1136604,Kolkata Knight Riders,Punjab Kings,459
987,1359512,Lucknow Super Giants,Punjab Kings,458
626,1082641,Mumbai Indians,Punjab Kings,453
791,1216527,Punjab Kings,Rajasthan Royals,449

#### Runs per team per match

In [224]:
runs_per_team = (final_df.groupby(['match_id', 'batting_team'])['total_runs'].sum().reset_index(name='runs'))
runs_per_team.head(5)

   match_id                 batting_team  runs
0    335982        Kolkata Knight Riders   222
1    335982  Royal Challengers Bangalore    82
2    335983          Chennai Super Kings   240
3    335983                 Punjab Kings   207
4    335984               Delhi Capitals   132

#### Top 10 batters

In [231]:
runs_per_batsman = (final_df.groupby('batter')['batsman_runs'].sum().reset_index(name = 'total_runs'))
runs_per_batsman

             batter  total_runs
0    A Ashish Reddy         280
1          A Badoni         634
2        A Chandila           4
3          A Chopra          53
4       A Choudhary          25
..              ...         ...
668   Yashpal Singh          47
669     Younis Khan           3
670   Yudhvir Singh          22
671    Yuvraj Singh        2754
672          Z Khan         117

[673 rows x 2 columns]

In [233]:
top_batsman = (runs_per_batsman.sort_values('total_runs', ascending=False).reset_index(drop = True))

top_batsman.insert(0, 'rank', top_batsman.index+1)
top_batsman.head(10)

   rank          batter  total_runs
0     1         V Kohli        8014
1     2        S Dhawan        6769
2     3       RG Sharma        6630
3     4       DA Warner        6567
4     5        SK Raina        5536
5     6        MS Dhoni        5243
6     7  AB de Villiers        5181
7     8        CH Gayle        4997
8     9      RV Uthappa        4954
9    10      KD Karthik        4843

#### Strike Rate of Batters

In [56]:
runs_per_batsman = (final_df.groupby('batter')['batsman_runs'].sum())
runs_per_batsman

batter
A Ashish Reddy     280
A Badoni           634
A Chandila           4
A Chopra            53
A Choudhary         25
                  ...
Yashpal Singh       47
Younis Khan          3
Yudhvir Singh       22
Yuvraj Singh      2754
Z Khan             117
Name: batsman_runs, Length: 673, dtype: int64

In [57]:
balls_faced_per_batsman = (final_df[final_df['extras_type'] != 'wides'].groupby('batter').size())
balls_faced_per_batsman

batter
A Ashish Reddy     193
A Badoni           473
A Chandila           7
A Chopra            71
A Choudhary         20
                  ...
Yashpal Singh       66
Younis Khan          7
Yudhvir Singh       16
Yuvraj Singh      2122
Z Khan             141
Length: 673, dtype: int64

In [58]:
batsman_stats = pd.concat(
    [runs_per_batsman, balls_faced_per_batsman],
    axis=1
)

batsman_stats.columns = ['total_runs', 'balls_faced']

In [59]:
batsman_stats

                total_runs  balls_faced
batter
A Ashish Reddy         280          193
A Badoni               634          473
A Chandila               4            7
A Chopra                53           71
A Choudhary             25           20
...                    ...          ...
Yashpal Singh           47           66
Younis Khan              3            7
Yudhvir Singh           22           16
Yuvraj Singh          2754         2122
Z Khan                 117          141

[673 rows x 2 columns]

In [60]:
batsman_stats['strike_rate'] = (batsman_stats['total_runs']/batsman_stats['balls_faced'])*100

In [61]:
batsman_stats.head()

                total_runs  balls_faced  strike_rate
batter
A Ashish Reddy         280          193   145.077720
A Badoni               634          473   134.038055
A Chandila               4            7    57.142857
A Chopra                53           71    74.647887
A Choudhary             25           20   125.000000

In [220]:
batsman_stats = batsman_stats.sort_values('strike_rate', ascending=False)

In [221]:
batsman_stats.head(10)

                 total_runs  balls_faced  strike_rate
batter
L Wood                    9            3   300.000000
B Stanlake                5            2   250.000000
J Fraser-McGurk         330          141   234.042553
R Sai Kishore            13            6   216.666667
Umar Gul                 39           19   205.263158
RS Sodhi                  4            2   200.000000
R Shepherd              115           63   182.539683
Naman Dhir              140           79   177.215190
LJ Wright               106           60   176.666667
Shahid Afridi            81           46   176.086957

#### Top 10 bowlers by Economy

In [63]:
runs_conceded = (final_df.groupby('bowler')['total_runs'].sum())
runs_conceded

bowler
A Ashish Reddy     400
A Badoni            37
A Chandila         245
A Choudhary        144
A Dananjaya         47
                  ...
Yash Dayal         933
Yash Thakur        702
Yudhvir Singh      125
Yuvraj Singh      1091
Z Khan            2860
Name: total_runs, Length: 530, dtype: int64

In [64]:
balls_bowled = (final_df[final_df['extra_runs'] == 0].groupby('bowler').size())
balls_bowled

bowler
A Ashish Reddy     258
A Badoni            24
A Chandila         232
A Choudhary        101
A Dananjaya         24
                  ...
Yash Dayal         571
Yash Thakur        394
Yudhvir Singh       70
Yuvraj Singh       858
Z Khan            2144
Length: 530, dtype: int64

In [65]:
overs_bowled = balls_bowled / 6

In [222]:
bowler_stats = pd.concat([runs_conceded, overs_bowled], axis = 1)

bowler_stats.columns = ['runs_conceded', 'overs_bowled']

bowler_stats['economy'] = bowler_stats['runs_conceded']/bowler_stats['overs_bowled']
bowler_stats = bowler_stats.sort_values('economy')

In [223]:
bowler_stats.head(10)

               runs_conceded  overs_bowled   economy
bowler
AC Gilchrist               0      0.166667  0.000000
R Ravindra                 7      2.000000  3.500000
Sachin Baby                8      1.666667  4.800000
AM Rahane                  5      1.000000  5.000000
NB Singh                  18      3.500000  5.142857
DJ Thornely               40      7.000000  5.714286
LA Carseldine              6      1.000000  6.000000
M Manhas                  42      7.000000  6.000000
SS Mundhe                  6      1.000000  6.000000
MW Short                  25      4.000000  6.250000

#### Most consistent batters

##### High average runs per match

In [67]:
runs_per_batsman

batter
A Ashish Reddy     280
A Badoni           634
A Chandila           4
A Chopra            53
A Choudhary         25
                  ...
Yashpal Singh       47
Younis Khan          3
Yudhvir Singh       22
Yuvraj Singh      2754
Z Khan             117
Name: batsman_runs, Length: 673, dtype: int64

In [68]:
# matches played by each batsman

matches_played = (final_df.groupby('batter')['match_id'].nunique())
matches_played

batter
A Ashish Reddy     23
A Badoni           35
A Chandila          2
A Chopra            6
A Choudhary         3
                 ...
Yashpal Singh       4
Younis Khan         1
Yudhvir Singh       4
Yuvraj Singh      126
Z Khan             27
Name: match_id, Length: 673, dtype: int64

In [69]:
batter_average = pd.concat([runs_per_batsman, matches_played], axis=1)

batter_average.columns = ['total_runs', 'matches_played']

batter_average['average_runs'] = batter_average['total_runs']/batter_average['matches_played']

In [205]:
batter_average = batter_average.sort_values('average_runs', ascending=False).head(10)
batter_average

                 total_runs  matches_played  average_runs
batter
Vivrant Sharma           69               1     69.000000
DP Conway               924              22     42.000000
B Sai Sudharsan        1034              25     41.360000
KL Rahul               4689             122     38.434426
LMP Simmons            1079              29     37.206897
J Fraser-McGurk         330               9     36.666667
RD Gaikwad             2380              65     36.615385
SE Marsh               2489              69     36.072464
HM Amla                 577              16     36.062500
DA Warner              6567             184     35.690217

##### Minimum number of matches played

In [71]:
matches_played = matches_played.reset_index(name = 'matches_played')

In [72]:
matches_played.sort_values('matches_played').head(10)

                   batter  matches_played
18                A Tomar               1
669           Younis Khan               1
667            Yash Dayal               1
656  X Thalaivan Sargunam               1
44              AJ Hosein               1
489            RR Bhatkal               1
5             A Dananjaya               1
496           RS Gavaskar               1
476               RG More               1
478            RJ Gleeson               1

#### Highest Individal score in a match

In [73]:
runs_per_match = final_df.groupby(['match_id','batting_team', 'bowling_team', 'batter'])['batsman_runs'].sum().reset_index(name = 'score')

In [74]:
runs_per_match.sort_values('score', ascending=False).head(1)

      match_id                 batting_team   bowling_team    batter  score
5309    598027  Royal Challengers Bangalore  Pune Warriors  CH Gayle    175

#### Boundary Analysis

##### Total no. of 4s

In [81]:
fours = final_df[(final_df['batsman_runs'] == 4) | (final_df['extra_runs'] >= 4)]
print("Total fours: ", len(fours))

Total fours:  30680

Total no. of 6s

In [82]:
sixes = final_df[(final_df['batsman_runs'] == 6)]
print("Total sixes: ", len(sixes))

Total sixes:  13051

In [89]:
batsman_boundaries = final_df[(final_df['batsman_runs'] == 4) | (final_df['batsman_runs'] == 6)]
batsman_boundaries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
10,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,SC Ganguly,6,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
11,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,Z Khan,SC Ganguly,4,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
16,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,P Kumar,SC Ganguly,4,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen

In [90]:
boundaries_per_batsman = (batsman_boundaries.groupby('batter').size().reset_index(name = 'boundaries'))

In [95]:
boundaries_per_batsman.sort_values('boundaries', ascending=False).head(10)

             batter  boundaries
532         V Kohli         981
437        S Dhawan         921
126       DA Warner         899
409       RG Sharma         880
109        CH Gayle         767
462        SK Raina         710
25   AB de Villiers         667
427      RV Uthappa         663
243      KD Karthik         627
323        MS Dhoni         615

#### Boundary Percentage

In [96]:
total_runs = (
    final_df
    .groupby('batter')['batsman_runs']
    .sum()
    .reset_index(name='total_runs')
)

In [97]:
total_runs

             batter  total_runs
0    A Ashish Reddy         280
1          A Badoni         634
2        A Chandila           4
3          A Chopra          53
4       A Choudhary          25
..              ...         ...
668   Yashpal Singh          47
669     Younis Khan           3
670   Yudhvir Singh          22
671    Yuvraj Singh        2754
672          Z Khan         117

[673 rows x 2 columns]

In [98]:
boundary_runs = (
    final_df[final_df['batsman_runs'].isin([4, 6])]
    .groupby('batter')['batsman_runs']
    .sum()
    .reset_index(name='boundary_runs')
)

In [99]:
boundary_runs

             batter  boundary_runs
0    A Ashish Reddy            154
1          A Badoni            328
2          A Chopra             28
3       A Choudhary             10
4        A Flintoff             32
..              ...            ...
558     YV Takawale            122
559   Yashpal Singh             20
560   Yudhvir Singh             16
561    Yuvraj Singh           1766
562          Z Khan             56

[563 rows x 2 columns]

In [101]:
runs_summary = (
    total_runs
    .merge(boundary_runs, on='batter', how='left')
    .fillna(0)
)

runs_summary['boundary_percentage'] = (
    runs_summary['boundary_runs'] / runs_summary['total_runs'] * 100
).round(2)

runs_summary.head(20)

            batter  total_runs  boundary_runs  boundary_percentage
0   A Ashish Reddy         280          154.0                55.00
1         A Badoni         634          328.0                51.74
2       A Chandila           4            0.0                 0.00
3         A Chopra          53           28.0                52.83
4      A Choudhary          25           10.0                40.00
5      A Dananjaya           4            0.0                 0.00
6       A Flintoff          62           32.0                51.61
7         A Kamboj           2            0.0                 0.00
8         A Kumble          35           12.0                34.29
9        A Manohar         231          144.0                62.34
10        A Mishra         381          154.0                40.42
11        A Mithun          34           22.0                64.71
12        A Mukund          19            4.0                21.05
13         A Nehra          41           18.0                43.90
14        A Nortje          49           24.0                48.98
15   A Raghuvanshi         163          112.0                68.71
16         A Singh           2            0.0                 0.00
17       A Symonds         974          542.0                55.65
18         A Tomar           4            4.0               100.00
19        A Uniyal           4            0.0                 0.00

#### Dot ball analysis

In [102]:
dot_ball = final_df[final_df['total_runs'] == 0]

In [105]:
print("Total dot balls: " ,len(dot_ball))

Total dot balls:  90438

In [112]:
dot_ball_per_bowler = dot_ball.groupby('bowler').size().reset_index(name='dot_balls')
dot_ball_per_bowler.sort_values('dot_balls', ascending=False).head(10)

              bowler  dot_balls
70           B Kumar       1632
436        SP Narine       1569
348         R Ashwin       1552
341        PP Chawla       1325
159  Harbhajan Singh       1263
188        JJ Bumrah       1228
366        RA Jadeja       1216
511        YS Chahal       1194
482         UT Yadav       1186
8           A Mishra       1185

#### Runs per over analysis

##### Average runs per over

In [ ]:
runs_per_over = (
    final_df
    .groupby(['match_id', 'inning', 'over'])['total_runs']
    .sum()
    .reset_index()
)

In [124]:
runs_per_over.head(10)

   match_id  inning  over  total_runs
0    335982       1     0           3
1    335982       1     1          18
2    335982       1     2           6
3    335982       1     3          23
4    335982       1     4          10
5    335982       1     5           1
6    335982       1     6           7
7    335982       1     7           5
8    335982       1     8           4
9    335982       1     9          10

In [122]:
average_runs_per_over = (
    runs_per_over
    .groupby('over')['total_runs']
    .mean()
    .reset_index(name='average_runs')
)

In [123]:
average_runs_per_over

    over  average_runs
0      0      6.157420
1      1      7.390489
2      2      8.186185
3      3      8.424062
4      4      8.496568
5      5      8.495186
6      6      6.816261
7      7      7.340836
8      8      7.667742
9      9      7.546377
10    10      7.775255
11    11      7.949721
12    12      8.039720
13    13      8.267229
14    14      8.617759
15    15      8.885041
16    16      9.324179
17    17      9.848439
18    18     10.093122
19    19     10.462309

##### High scoring overs

In [126]:
average_runs_per_over.sort_values('average_runs', ascending=False).head()

    over  average_runs
19    19     10.462309
18    18     10.093122
17    17      9.848439
16    16      9.324179
15    15      8.885041

#### Power play Analysis

In [129]:
power_play_runs = final_df[(final_df['over'] >= 0) & (final_df['over'] <= 5)]['total_runs'].sum()
print("Total power play runs: " ,power_play_runs)

Total power play runs:  103217

In [130]:
powerplay_df = final_df[(final_df['over'] >= 0) & (final_df['over'] <= 5)]
powerplay_df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260888,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,5,2,VR Iyer,T Natarajan,Rahmanullah Gurbaz,4,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260889,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,5,3,VR Iyer,T Natarajan,Rahmanullah Gurbaz,6,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260890,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,5,4,VR Iyer,T Natarajan,Rahmanullah Gurbaz,4,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260891,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,5,5,VR Iyer,T Natarajan,Rahmanullah Gurbaz,1,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260892,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,5,6,Rahmanullah Gurbaz,T Natarajan,VR Iyer,1,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon

In [135]:
powerplay_runs_per_team = (powerplay_df.groupby('batting_team')['total_runs'].sum()).reset_index(name = 'runs_in_powerplay')
powerplay_runs_per_team

                   batting_team  runs_in_powerplay
0           Chennai Super Kings              10991
1               Deccan Chargers               3417
2                Delhi Capitals              12069
3                 Gujarat Lions               1559
4                Gujarat Titans               2184
5          Kochi Tuskers Kerala                680
6         Kolkata Knight Riders              11941
7          Lucknow Super Giants               2080
8                Mumbai Indians              12225
9                 Pune Warriors               1895
10                 Punjab Kings              11795
11             Rajasthan Royals              10226
12      Rising Pune Supergiants               1423
13  Royal Challengers Bangalore              11795
14          Sunrisers Hyderabad               8937

In [136]:
powerplay_runs_per_team.sort_values('runs_in_powerplay', ascending=False).head(5)

                   batting_team  runs_in_powerplay
8                Mumbai Indians              12225
2                Delhi Capitals              12069
6         Kolkata Knight Riders              11941
10                 Punjab Kings              11795
13  Royal Challengers Bangalore              11795

#### Death over analysis

In [137]:
# total runs(16-20 overs)

death_over_df = final_df[(final_df['over'] >= 16) & (final_df['over'] <= 19)]
death_over_df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
100,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,1,BB McCullum,Z Khan,DJ Hussey,1,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
101,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,2,DJ Hussey,Z Khan,BB McCullum,2,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
102,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,3,DJ Hussey,Z Khan,BB McCullum,1,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
103,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,4,BB McCullum,Z Khan,DJ Hussey,6,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
104,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,5,BB McCullum,Z Khan,DJ Hussey,2,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260848,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,5,JD Unadkat,SP Narine,PJ Cummins,0,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260849,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,6,B Kumar,SP Narine,PJ Cummins,0,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260850,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,1,PJ Cummins,AD Russell,B Kumar,0,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260851,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,2,PJ Cummins,AD Russell,B Kumar,0,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon
260852,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,3,PJ Cummins,AD Russell,B Kumar,0,...,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,J Madanagopal,Nitin Menon

In [138]:
death_over_runs = death_over_df['total_runs'].sum()
print("Total runs in death overs: " ,death_over_runs)

Total runs in death overs:  75412

##### Best team in death overs

In [226]:
death_over_runs_per_team = death_over_df.groupby('batting_team')['total_runs'].sum().reset_index(name = 'runs_in_death_overs')
death_over_runs_per_team

                   batting_team  runs_in_death_overs
0           Chennai Super Kings                 9061
1               Deccan Chargers                 2539
2                Delhi Capitals                 8184
3                 Gujarat Lions                  921
4                Gujarat Titans                 1823
5          Kochi Tuskers Kerala                  337
6         Kolkata Knight Riders                 8053
7          Lucknow Super Giants                 1718
8                Mumbai Indians                 9598
9                 Pune Warriors                 1360
10                 Punjab Kings                 8274
11             Rajasthan Royals                 7281
12      Rising Pune Supergiants                  998
13  Royal Challengers Bangalore                 9028
14          Sunrisers Hyderabad                 6237

In [227]:
death_over_runs_per_team = death_over_runs_per_team.sort_values('runs_in_death_overs', ascending=False)
death_over_runs_per_team

                   batting_team  runs_in_death_overs
8                Mumbai Indians                 9598
0           Chennai Super Kings                 9061
13  Royal Challengers Bangalore                 9028
10                 Punjab Kings                 8274
2                Delhi Capitals                 8184
6         Kolkata Knight Riders                 8053
11             Rajasthan Royals                 7281
14          Sunrisers Hyderabad                 6237
1               Deccan Chargers                 2539
4                Gujarat Titans                 1823
7          Lucknow Super Giants                 1718
9                 Pune Warriors                 1360
12      Rising Pune Supergiants                  998
3                 Gujarat Lions                  921
5          Kochi Tuskers Kerala                  337

##### Best batter in death

In [142]:
runs_in_death_per_batter = death_over_df.groupby('batter')['total_runs'].sum().reset_index(name = 'runs_in_death')
runs_in_death_per_batter

             batter  runs_in_death
0    A Ashish Reddy            199
1          A Badoni            363
2        A Chandila              4
3       A Choudhary             24
4       A Dananjaya              4
..              ...            ...
578      Yash Dayal              0
579   Yashpal Singh             11
580   Yudhvir Singh              1
581    Yuvraj Singh            641
582          Z Khan            105

[583 rows x 2 columns]

In [143]:
runs_in_death_per_batter.sort_values('runs_in_death', ascending=False).head(10)

             batter  runs_in_death
328        MS Dhoni           2926
242      KA Pollard           1804
247      KD Karthik           1647
415       RA Jadeja           1501
24   AB de Villiers           1477
421       RG Sharma           1218
182       HH Pandya           1195
31       AD Russell           1142
550         V Kohli           1139
124       DA Miller           1035

#### Run Distribution per Inning

In [144]:
innings_runs = (
    final_df
    .groupby(['match_id', 'inning'])['total_runs']
    .sum()
    .reset_index(name='innings_runs')
)

innings_runs

      match_id  inning  innings_runs
0       335982       1           222
1       335982       2            82
2       335983       1           240
3       335983       2           207
4       335984       1           129
...        ...     ...           ...
2212   1426310       2           174
2213   1426311       1           175
2214   1426311       2           139
2215   1426312       1           113
2216   1426312       2           114

[2217 rows x 3 columns]

In [148]:
overall_innings_avg = (
    innings_runs[innings_runs['inning'].isin([1,2])]
    .groupby('inning')['innings_runs']
    .mean()
    .reset_index(name='avg_runs')
)

overall_innings_avg

   inning    avg_runs
0       1  165.547032
1       2  152.194139

#### Toss Impact Analysis

In [149]:
innings_runs = (
    final_df
    .groupby(['match_id', 'inning', 'batting_team'])['total_runs']
    .sum()
    .reset_index(name='innings_runs')
)

In [150]:
innings_runs

      match_id  inning                 batting_team  innings_runs
0       335982       1        Kolkata Knight Riders           222
1       335982       2  Royal Challengers Bangalore            82
2       335983       1          Chennai Super Kings           240
3       335983       2                 Punjab Kings           207
4       335984       1             Rajasthan Royals           129
...        ...     ...                          ...           ...
2212   1426310       2             Rajasthan Royals           174
2213   1426311       1          Sunrisers Hyderabad           175
2214   1426311       2             Rajasthan Royals           139
2215   1426312       1          Sunrisers Hyderabad           113
2216   1426312       2        Kolkata Knight Riders           114

[2217 rows x 4 columns]

In [155]:
innings_runs = innings_runs.merge(
    matches_df[['id', 'toss_winner']],
    left_on='match_id',
    right_on='id',
    how='left'
)

In [157]:
innings_runs.head()

,match_id,inning,batting_team,innings_runs,id,toss_winner
0,335982,1,Kolkata Knight Riders,222,335982,Royal Challengers Bangalore
1,335982,2,Royal Challengers Bangalore,82,335982,Royal Challengers Bangalore
2,335983,1,Chennai Super Kings,240,335983,Chennai Super Kings
3,335983,2,Punjab Kings,207,335983,Chennai Super Kings
4,335984,1,Rajasthan Royals,129,335984,Rajasthan Royals

In [159]:
innings_runs['team_type'] = innings_runs.apply(
    lambda x: 'toss_winner'
    if x['batting_team'] == x['toss_winner']
    else 'opponent',
    axis=1
)

innings_runs.head()

,match_id,inning,batting_team,innings_runs,id,toss_winner,team_type
0,335982,1,Kolkata Knight Riders,222,335982,Royal Challengers Bangalore,opponent
1,335982,2,Royal Challengers Bangalore,82,335982,Royal Challengers Bangalore,toss_winner
2,335983,1,Chennai Super Kings,240,335983,Chennai Super Kings,toss_winner
3,335983,2,Punjab Kings,207,335983,Chennai Super Kings,opponent
4,335984,1,Rajasthan Royals,129,335984,Rajasthan Royals,toss_winner

In [160]:
toss_comparison = (
    innings_runs
    .groupby('team_type')['innings_runs']
    .mean()
    .reset_index(name='avg_runs')
)

toss_comparison

     team_type    avg_runs
0     opponent  158.171318
1  toss_winner  155.032362

Yes winning toss has an advntage, as teams end up scoring more and win the match by winning the toss

#### Player of Match Contribution

In [174]:
batsman_innings_runs = (
    final_df
    .groupby(['match_id', 'inning', 'batter'])['batsman_runs']
    .sum()
    .reset_index(name='runs')
)

In [175]:
batsman_innings_runs.head()

   match_id  inning           batter  runs
0    335982       1      BB McCullum   158
1    335982       1        DJ Hussey    12
2    335982       1  Mohammad Hafeez     5
3    335982       1       RT Ponting    20
4    335982       1       SC Ganguly    10

In [176]:
top_batsman_each_innings = (
    batsman_innings_runs
    .sort_values(['match_id', 'inning', 'runs'], ascending=[True, True, False])
    .groupby(['match_id', 'inning'])
    .head(1)
    .reset_index(drop=True)
)

top_batsman_each_innings.head(10)

   match_id  inning       batter  runs
0    335982       1  BB McCullum   158
1    335982       2      P Kumar    18
2    335983       1   MEK Hussey   116
3    335983       2     JR Hopes    71
4    335984       1    RA Jadeja    29
5    335984       2    G Gambhir    58
6    335985       1   RV Uthappa    48
7    335985       2   MV Boucher    39
8    335986       1    A Symonds    32
9    335986       2    DJ Hussey    38

In [177]:
top_batsman_each_innings = top_batsman_each_innings.merge(matches_df[['id', 'player_of_match']], left_on='match_id', right_on='id', how='left')

In [180]:
top_batsman_each_innings.head(10)

   match_id  inning       batter  runs      id player_of_match
0    335982       1  BB McCullum   158  335982     BB McCullum
1    335982       2      P Kumar    18  335982     BB McCullum
2    335983       1   MEK Hussey   116  335983      MEK Hussey
3    335983       2     JR Hopes    71  335983      MEK Hussey
4    335984       1    RA Jadeja    29  335984     MF Maharoof
5    335984       2    G Gambhir    58  335984     MF Maharoof
6    335985       1   RV Uthappa    48  335985      MV Boucher
7    335985       2   MV Boucher    39  335985      MV Boucher
8    335986       1    A Symonds    32  335986       DJ Hussey
9    335986       2    DJ Hussey    38  335986       DJ Hussey

yes most of the time player of the match contribute with highest runs. But sometimes player of the match also goes to the bowler who takes highest wickets or with best economy

#### Venue wise analysis

##### Total matches per venue

In [182]:
final_df['venue'] = final_df['venue'].str.split(',').str[0]

In [185]:
final_df['venue'].unique()

array(['M Chinnaswamy Stadium', 'Punjab Cricket Association Stadium',
       'Feroz Shah Kotla', 'Wankhede Stadium', 'Eden Gardens',
       'Sawai Mansingh Stadium', 'Rajiv Gandhi International Stadium',
       'MA Chidambaram Stadium', 'Dr DY Patil Sports Academy', 'Newlands',
       "St George's Park", 'Kingsmead', 'SuperSport Park', 'Buffalo Park',
       'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium', 'Sardar Patel Stadium',
       'Barabati Stadium', 'Vidarbha Cricket Association Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Maharashtra Cricket Association Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium', 'Arun Jaitley Stadium',
       'Narendra Modi Stadium', 'Zayed Cricket Stadium',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'Barsapara Cricket Stadium',
       'Maharaja Yadavindra Singh International Cricket Stadium'],
      dtype=object)

In [186]:
matches_per_venue = final_df.groupby('venue')['id'].size().reset_index(name = 'matches_per_venue')

In [187]:
matches_per_venue

                                                venue  matches_per_venue
0                                Arun Jaitley Stadium               7319
1                                    Barabati Stadium               1695
2                           Barsapara Cricket Stadium                739
3   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...               3283
4                                   Brabourne Stadium               6526
5                                        Buffalo Park                715
6                               De Beers Diamond Oval                726
7                          Dr DY Patil Sports Academy               8898
8   Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...               3537
9                 Dubai International Cricket Stadium              11229
10                                       Eden Gardens              21846
11                                   Feroz Shah Kotla              13950
12                                         Green Park                921
13       Himachal Pradesh Cricket Association Stadium               3141
14                             Holkar Cricket Stadium               1965
15                 JSCA International Stadium Complex               1671
16                                          Kingsmead               3643
17                              M Chinnaswamy Stadium              18330
18                              M.Chinnaswamy Stadium               3494
19                             MA Chidambaram Stadium              20706
20  Maharaja Yadavindra Singh International Cricke...               1235
21            Maharashtra Cricket Association Stadium               8414
22                              Narendra Modi Stadium               5660
23                                      Nehru Stadium               1155
24                              New Wanderers Stadium               1940
25                                           Newlands               1539
26                                    OUTsurance Oval                500
27       Punjab Cricket Association IS Bindra Stadium               6210
28                 Punjab Cricket Association Stadium               8266
29                 Rajiv Gandhi International Stadium              18355
30                               Sardar Patel Stadium               2893
31             Saurashtra Cricket Association Stadium               2381
32                             Sawai Mansingh Stadium              13520
33   Shaheed Veer Narayan Singh International Stadium               1431
34                            Sharjah Cricket Stadium               6672
35                               Sheikh Zayed Stadium               6925
36                                   St George's Park               1677
37                         Subrata Roy Sahara Stadium               3825
38                                    SuperSport Park               2866
39               Vidarbha Cricket Association Stadium                742
40                                   Wankhede Stadium              28506
41                              Zayed Cricket Stadium               1874

##### Average runs scored in each venue

In [192]:
venue_runs = (
    final_df
    .groupby(['venue', 'match_id'])['total_runs']
    .sum()
    .reset_index(name='venue_runs_per_match')
)

In [193]:
venue_runs

                      venue  match_id  venue_runs_per_match
0      Arun Jaitley Stadium   1136582                   282
1      Arun Jaitley Stadium   1136586                   383
2      Arun Jaitley Stadium   1136592                   342
3      Arun Jaitley Stadium   1136602                   378
4      Arun Jaitley Stadium   1136605                   368
...                     ...       ...                   ...
1090  Zayed Cricket Stadium   1254095                   278
1091  Zayed Cricket Stadium   1254096                   314
1092  Zayed Cricket Stadium   1254097                   275
1093  Zayed Cricket Stadium   1254098                   343
1094  Zayed Cricket Stadium   1254099                   272

[1095 rows x 3 columns]

In [209]:
average_runs_each_venue = (
    venue_runs
    .groupby('venue')['venue_runs_per_match']
    .mean()
    .reset_index(name='avg_runs_per_venue')
    .round(2)
)
average_runs_each_venue.head(20)

                                                venue  avg_runs_per_venue
0                                Arun Jaitley Stadium              354.47
1                                    Barabati Stadium              325.43
2                           Barsapara Cricket Stadium              339.67
3   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...              306.71
4                                   Brabourne Stadium              344.63
5                                        Buffalo Park              266.33
6                               De Beers Diamond Oval              299.00
7                          Dr DY Patil Sports Academy              307.65
8   Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...              303.07
9                 Dubai International Cricket Stadium              314.13
10                                       Eden Gardens              319.82
11                                   Feroz Shah Kotla              307.02
12                                         Green Park              324.50
13       Himachal Pradesh Cricket Association Stadium              339.38
14                             Holkar Cricket Stadium              319.11
15                 JSCA International Stadium Complex              293.71
16                                          Kingsmead              290.20
17                              M Chinnaswamy Stadium              323.86
18                              M.Chinnaswamy Stadium              341.80
19                             MA Chidambaram Stadium              314.19

#### City wise Scoring Trends

In [197]:
city_runs = (
    final_df
    .groupby(['city', 'match_id'])['total_runs']
    .sum()
    .reset_index(name='city_runs_per_match')
)
city_runs

               city  match_id  city_runs_per_match
0         Abu Dhabi    729279                  285
1         Abu Dhabi    729283                  411
2         Abu Dhabi    729285                  268
3         Abu Dhabi    729293                  261
4         Abu Dhabi    729305                  141
...             ...       ...                  ...
1090  Visakhapatnam    981005                  345
1091  Visakhapatnam   1181766                  327
1092  Visakhapatnam   1181767                  298
1093  Visakhapatnam   1422131                  362
1094  Visakhapatnam   1422134                  438

[1095 rows x 3 columns]

##### Average runs per city

In [198]:
average_runs_each_city = (
    city_runs
    .groupby('city')['city_runs_per_match']
    .mean()
    .reset_index(name='avg_runs_per_city')
    .round(2)
)
average_runs_each_city.head(20)

            city  avg_runs_per_city
0      Abu Dhabi             306.27
1      Ahmedabad             331.03
2      Bangalore             311.74
3      Bengaluru             360.31
4   Bloemfontein             264.50
5      Cape Town             256.71
6      Centurion             304.42
7     Chandigarh             325.64
8        Chennai             314.19
9        Cuttack             325.43
10         Delhi             322.83
11    Dharamsala             339.38
12         Dubai             314.13
13        Durban             290.20
14   East London             266.33
15      Guwahati             339.67
16     Hyderabad             315.09
17        Indore             319.11
18        Jaipur             310.26
19  Johannesburg             286.50

##### High Scoring city

In [201]:
high_scoring_city = final_df.groupby('venue')['total_runs'].sum().reset_index(name = 'total_runs_per_city')
high_scoring_city.sort_values('total_runs_per_city', ascending=False).head(10)

                                      venue  total_runs_per_city
40                         Wankhede Stadium                38994
10                             Eden Gardens                29743
19                   MA Chidambaram Stadium                26706
17                    M Chinnaswamy Stadium                25585
29       Rajiv Gandhi International Stadium                24262
11                         Feroz Shah Kotla                18421
32                   Sawai Mansingh Stadium                17685
9       Dubai International Cricket Stadium                14450
7                Dr DY Patil Sports Academy                11383
21  Maharashtra Cricket Association Stadium                11115

#### Season wise analysis

In [250]:
final_df['year'] = final_df['date'].dt.year
final_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2,year
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen,2008
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen,2008
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen,2008
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen,2008
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen,2008

In [203]:
runs_per_season = final_df.groupby('year')['total_runs'].sum().reset_index(name = 'runs_per_season')
runs_per_season

    year  runs_per_season
0   2008            17937
1   2009            16353
2   2010            18883
3   2011            21154
4   2012            22453
5   2013            22602
6   2014            18931
7   2015            18353
8   2016            18862
9   2017            18786
10  2018            19901
11  2019            19434
12  2020            19416
13  2021            18637
14  2022            24395
15  2023            25688
16  2024            25971

In each season we see growth in total runs

### Derived Insights

##### Most consistent batsmen

In [206]:
batter_average.head(5)

                 total_runs  matches_played  average_runs
batter
Vivrant Sharma           69               1     69.000000
DP Conway               924              22     42.000000
B Sai Sudharsan        1034              25     41.360000
KL Rahul               4689             122     38.434426
LMP Simmons            1079              29     37.206897

##### Best Death over team

In [208]:
death_over_runs_per_team

                   batting_team  runs_in_death_overs
8                Mumbai Indians                 9598
0           Chennai Super Kings                 9061
13  Royal Challengers Bangalore                 9028
10                 Punjab Kings                 8274
2                Delhi Capitals                 8184

##### High scoring venue

In [212]:
high_scoring_venues = average_runs_each_venue.sort_values('avg_runs_per_venue', ascending=False).head()

In [213]:
high_scoring_venues

                                           venue  avg_runs_per_venue
0                           Arun Jaitley Stadium              354.47
4                              Brabourne Stadium              344.63
18                         M.Chinnaswamy Stadium              341.80
27  Punjab Cricket Association IS Bindra Stadium              341.42
2                      Barsapara Cricket Stadium              339.67

### Saving dataframes to csv files

In [229]:
runs_per_match.to_csv('output/runs_per_match.csv', index=False)

In [235]:
top_batsman.to_csv('output/top_batsman.csv', index = False)

In [239]:
batsman_stats.to_csv('output/strike_rate.csv')

In [241]:
bowler_stats.to_csv('output/economy.csv')

In [244]:
runs_per_team.to_csv('output/team_scores.csv')

In [249]:
death_over_runs_per_team.to_csv('output/death_overs.csv')